### ISSUE TITLE
Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#131]
Hi, I'm getting this error:

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Mon Nov  9 08:26:00 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 94
    output: /gpfs/scratch/evrong01/droptest3/root/processed_data/aberrant_splicing/datasets/cache/raw-GTEX100/sample_tmp/splitCounts/sample_GTEX-11PRG_RNA.done
    log: /gpfs/scratch/evrong01/droptest3/.drop/tmp/AS/GTEX100/splitReads/GTEX-11PRG_RNA.Rds (check log file(s) for error message)

**Comment by gevro** [comment]
I think you need to add to your code to install and to load it with library(BSgenome.Hsapiens.UCSC.hg38)

https://bioconductor.org/packages/release/data/annotation/html/BSgenome.Hsapiens.UCSC.hg38.html

**Comment by vyepez88** [comment]
Hi, I modified the code in that script to load the correct library depending on the genome build. It will be reflected in the next update (later this week).

**Comment by vyepez88** [comment]
Hi, it's fixed now in the dev branch:
pip install git+https://github.com/gagneurlab/drop.git@dev

**Comment by gevro** [comment]
Still not working, same error:

Load packages
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted

**Comment by vyepez88** [comment]
can you please install the BSgenome.Hsapiens.UCSC.hg38 package manually? we're now developing a solution that installs each package depending on the config file, but it's not ready yet.

**Comment by gevro** [comment]
I installed manually, but still the same error. I confirmed I can load the library with library(). I suspect that your code is still not fixed and is not loading the library before trying to use it.

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted

**Comment by gevro** [comment]
Hi, Is there any update on this? Thanks.

**Comment by vyepez88** [comment]
Hi, can you try again installing the dev branch?
Also, be sure to have hg38 in genomeAssembly parameter in the config file.

**Comment by gevro** [comment]
Still not working. Perhaps it would help if you test DROP on a clean computer image without anything installed in order to discover any dependencies and issues. Because there might be dependencies that are already installed on your dev computer that are not revealed in your testing.

```
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Tue Nov 17 10:53:47 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 92
    output: /gpfs/scratch/evrong01/droptest3/root/processed_data/aberrant_splicing/datasets/cache/raw-GTEX100/sample_tmp/splitCounts/sample_GTEX-11ZTT_RNA.done
    log: /gpfs/scratch/evrong01/droptest3/.drop/tmp/AS/GTEX100/splitReads/GTEX-11ZTT_RNA.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 127 of /tmp/tmpcnkvor86:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/scratch/evrong01/droptest3/.snakemake/scripts/tmpolmxz_ya.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmpcnkvor86", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by vyepez88** [comment]
Hi, we fixed it in this commit in the dev branch: https://github.com/gagneurlab/drop/commit/783d541887f49d139c9f39bcb2d5da04df0b9c6c#diff-a6fa7a865638d4ec707fce7bc7b8e321be541fc15fdd1a1ee16d32a12cada0e9

can you please execute the following code in a new R session:
```
library(BSgenome)
genome <- "BSgenome.Hsapiens.UCSC.hg38"
genome <- getBSgenome(genome)
genome
```

what do you get?

**Comment by gevro** [comment]
I installed from dev just now again, but still getting the same error:
```
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Wed Nov 18 11:30:52 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 92
    output: /gpfs/scratch/evrong01/droptest3/root/processed_data/aberrant_splicing/datasets/cache/raw-GTEX100/sample_tmp/splitCounts/sample_GTEX-11DXX_RNA.done
    log: /gpfs/scratch/evrong01/droptest3/.drop/tmp/AS/GTEX100/splitReads/GTEX-11DXX_RNA.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 127 of /tmp/tmps9rbb91m:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/scratch/evrong01/droptest3/.snakemake/scripts/tmpre6nljh6.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmps9rbb91m", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/droptest3/.snakemake/log/2020-11-18T113032.203004.snakemake.log
```

I also ran your commands, and I get this:
```
Loading required package: rtracklayer
> genome <- "BSgenome.Hsapiens.UCSC.hg38"
> genome <- getBSgenome(genome)
> genome
Human genome:
# organism: Homo sapiens (Human)
# provider: UCSC
# provider version: hg38
# release date: Dec. 2017
# release name: Genome Reference Consortium GRCh38.p12
# 595 sequences:
#   chr1                    chr2                    chr3                   
#   chr4                    chr5                    chr6                   
#   chr7                    chr8                    chr9                   
#   chr10                   chr11                   chr12                  
#   chr13                   chr14                   chr15                  
#   ...                     ...                     ...                    
#   chr19_KV575254v1_alt    chr19_KV575255v1_alt    chr19_KV575256v1_alt   
#   chr19_KV575257v1_alt    chr19_KV575258v1_alt    chr19_KV575259v1_alt   
#   chr19_KV575260v1_alt    chr22_KN196485v1_alt    chr22_KN196486v1_alt   
#   chr22_KQ458387v1_alt    chr22_KQ458388v1_alt    chr22_KQ759761v1_alt   
#   chrX_KV766199v1_alt                                                    
# (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator
# to access a given sequence)
```

**Comment by gevro** [comment]
Hi, Any update on this? Thanks!

**Comment by gevro** [comment]
Hi, Any update on this? Thanks!

**Comment by gevro** [comment]
Hi, Is this issue going to be fixed in the upcoming release? When will that be?
Thanks.

**Comment by mumichae** [comment]
can please check if you get the same error on the demo project?

Also make sure that you updated drop properly and check with `drop --version`. Did you use
```
pip install .
```
on the correct commit?

**Comment by gevro** [comment]
Demo works fine. It is only when using hg38 that this happens.
Is there a commit that fixed this problem that I can try?

**Comment by vyepez88** [comment]
In the demo, can you change the genomeAssembly parameter to hg38 and run the aberrant splicing module? it will give this warning:
```
Warning message:
In countSplitReads(sampleID = sample_id, fds = fds, NcpuPerSample = snakemake@threads,  :
  Not counting chromosome(s) chr21 in sample HG00096.1.M_111124_6_trunc as it has a different length in the bamFile of this sample than in the provided genome.
Wed Dec  9 14:06:41 2020: fraser, HG00096.1.M_111124_6_trunc no. splice junctions (split counts) = 0
```
but at least go through the counting script.

**Comment by gevro** [comment]
With demo set to hg38, I get the same error that I get for my project. See below.
The issue is that drop conda environment does not handle or set up hg38.
Will this be fixed?
Thanks.

```
Load packages
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Wed Dec  9 22:02:48 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 93
    output: /gpfs/scratch/evrong01/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_HG00150.4.M_120208_7_trunc.done
    log: /gpfs/scratch/evrong01/drop_demo/.drop/tmp/AS/fraser/splitReads/HG00150.4.M_120208_7_trunc.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 127 of /tmp/tmp05cc7dl2:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/scratch/evrong01/drop_demo/.snakemake/scripts/tmpa2mvvxdo.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmp05cc7dl2", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/drop_demo/.snakemake/log/2020-12-09T220053.661299.snakemake.log
```

**Comment by gevro** [comment]
Have any other users been able to get hg38 to work?

**Comment by c-mertes** [comment]
I'm currently moving from california to germany. Hence I'm sorry for not responding on this. I will have time again after Christmas. Sorry about that.

**Comment by vyepez88** [comment]
@gevro, can you please try this branch? https://github.com/gagneurlab/drop/tree/bsgenome

**Comment by gevro** [comment]
Same error for demo when I change it to 'hg38'.

I'm not sure why this is happening. Can you just add default installation and library load for 'BSgenome.Hsapiens.UCSC.hg38'?

```
Load packages
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Tue Dec 15 00:06:35 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 93
    output: /gpfs/scratch/evrong01/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_HG00150.4.M_120208_7_trunc.done
    log: /gpfs/scratch/evrong01/drop_demo/.drop/tmp/AS/fraser/splitReads/HG00150.4.M_120208_7_trunc.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 127 of /tmp/tmpkvbdbnyc:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/scratch/evrong01/drop_demo/.snakemake/scripts/tmp3c064y1t.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmpkvbdbnyc", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/drop_demo/.snakemake/log/2020-12-15T000432.601378.snakemake.log
```

**Comment by mumichae** [comment]
How did you install drop? Are you working with the Git repository? Make sure that you followed all the steps.

```
# in Git repository
pip install -e .
# in project directory
drop update
```

It could be that you aren't using the latest changes in your project directory if you didn't do the last step.

**Comment by gevro** [comment]
Thanks. I installed drop from the git repository. Then I made a new drop_demo directory. It still doesn't work for hg38.

My recommendation to fix this and other similar bugs is to set up a clean linux system without anything installed on it, then install and test 'drop' to reveal unknown dependencies that might be hidden when testing on the development systems.

**Comment by gevro** [comment]
Hi, Is there any update about this? It's the last step in getting your tool to work on our cases/systems.
Thanks.

**Comment by vyepez88** [comment]
can you please try this branch? https://github.com/gagneurlab/drop/tree/bsgenome38
it installs BSgenome38 directly. I tried it on a clean system and it went through.

**Comment by gevro** [comment]
Hi, It still doesn't work.
I activated my drop conda profile
I installed like this: pip install git+https://github.com/gagneurlab/drop.git@bsgenome38

I made a new drop demo directory.
I changed genome to hg38.

Am I doing something wrong?

Error:
```
Load packages
Loading required package: BSgenome
Loading required package: rtracklayer

Attaching package: ‘rtracklayer’

The following object is masked from ‘package:plotly’:

    export

Error: object 'BSgenome.Hsapiens.UCSC.hg38' not found
Execution halted
[Thu Dec 24 10:01:39 2020]
Error in rule AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R:
    jobid: 93
    output: /gpfs/home/evrong01/drop_demo/Output/processed_data/aberrant_splicing/datasets/cache/raw-fraser/sample_tmp/splitCounts/sample_HG00176.4.M_120208_2_trunc.done
    log: /gpfs/home/evrong01/drop_demo/.drop/tmp/AS/fraser/splitReads/HG00176.4.M_120208_2_trunc.Rds (check log file(s) for error message)

RuleException:
CalledProcessError in line 127 of /tmp/tmpfwqhjajh:
Command 'set -euo pipefail;  Rscript --vanilla /gpfs/home/evrong01/drop_demo/.snakemake/scripts/tmpkmiwnrjn.01_1_countRNA_splitReads_samplewise.R' returned non-zero exit status 1.
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2208, in run_wrapper
  File "/tmp/tmpfwqhjajh", line 127, in __rule_AberrantSplicing_pipeline_Counting_01_1_countRNA_splitReads_samplewise_R
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/gpfs/home/evrong01/evronylab/bin/drop-conda/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2239, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/home/evrong01/drop_demo/.snakemake/log/2020-12-24T095927.407323.snakemake.log

```

**Comment by gevro** [comment]
Note also:  Manually running R from the conda environment and doing: "library(BSgenome.Hsapiens.UCSC.hg38)" works fine.

This means that the problem is not installing BSgenome.Hsapiens.UCSC.hg38.

The problem is that your drop script is not running library(BSgenome.Hsapiens.UCSC.hg38) at the right step.

**Comment by gevro** [comment]
I think I found your bug. See below. The error points to an issue in: 01_1_countRNA_splitReads_samplewise.R.

When I look at this code: ./Scripts/AberrantSplicing/pipeline/Counting/01_1_countRNA_splitReads_samplewise.R
it has the line "library(BSgenome.Hsapiens.UCSC.hg19)".

So that is the bug. The correct library is not being loaded depending on config.yaml genome configuration.

```
saveRDS(snakemake, snakemake@log$snakemake)
source(snakemake@params$setup, echo=FALSE)
library(BSgenome.Hsapiens.UCSC.hg19)

dataset    <- snakemake@wildcards$dataset
workingDir <- snakemake@params$workingDir
params <- snakemake@config$aberrantSplicing


# Read FRASER object
fds <- loadFraserDataSet(dir=workingDir, name=paste0("raw-", dataset))

# Get sample id from wildcard
sample_id <- snakemake@wildcards[["sample_id"]]

# If data is not strand specific, add genome info
genome <- NULL

if(strandSpecific(fds) == 0){
  if(snakemake@config$genomeAssembly == 'hg19'){
    genome <- BSgenome.Hsapiens.UCSC.hg19
  } else if(snakemake@config$genomeAssembly == 'hg38'){
    genome <- BSgenome.Hsapiens.UCSC.hg38
  }
}
```

**Comment by vyepez88** [comment]
did you do `drop update`?
this is how the 01_1_countRNA script looks like in the BSgenome38 branch: https://github.com/gagneurlab/drop/blob/bsgenome38/drop/modules/aberrant-splicing-pipeline/Counting/01_1_countRNA_splitReads_samplewise.R

**Comment by gevro** [comment]
I made an entirely new drop demo directory:
mkdir drop_demo
cd drop_demo
drop demo

Why would I need to do drop update if it is a new drop directory?

**Comment by gevro** [comment]
In any case, doing drop update doesn't change the code of that R script. See below.

Is this the correct command to install the bsgenome38 branch?
pip install git+https://github.com/gagneurlab/drop.git@bsgenome38


```
"#'---

saveRDS(snakemake, snakemake@log$snakemake)
source(snakemake@params$setup, echo=FALSE)
library(BSgenome.Hsapiens.UCSC.hg19)

dataset    <- snakemake@wildcards$dataset
workingDir <- snakemake@params$workingDir
params <- snakemake@config$aberrantSplicing
```

**Comment by gevro** [comment]
Looks like pip install --upgrade git+https://github.com/gagneurlab/drop.git@bsgenome38 is required to get the updated version.

**Comment by vyepez88** [comment]
- you indeed don't need to drop update if it's a new directory
- we've always used `pip install git+`, without the `--upgrade`
did it work?

**Comment by gevro** [comment]
--upgrade successfully updated the script. Might be a difference in my pip version. Would be good to add this to your documentation, otherwise people might not be upgrading properly.

Now that it was upgraded properly, I'm getting this error:
```
install MafDb.gnomAD.r2.1.hs37d5
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'MafDb.gnomAD.r2.1.hs37d5'
trying URL 'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/MafDb.gnomAD.r2.1.hs37d5_3.10.0.tar.gz'
Content type 'application/x-gzip' length 6046874367 bytes (5766.7 MB)
======================
downloaded 2639.6 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.11/data/annotation/src/contrib/MafDb.gnomAD.r2.1.hs37d5_3.10.0.tar.gz' failed
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘MafDb.gnomAD.r2.1.hs37d5’ failed
installed MafDb.gnomAD.r2.1.hs37d5
```

UPDATE: For this error, manually downloading the tar.gz from here and installing manually from source works: https://bioconductor.org/packages/release/data/annotation/html/MafDb.gnomAD.r2.1.hs37d5.html . For some reason the BiocManager::install command keeps failing in the download of the package.

UPDATE 2: Same issue and same fix for MafDb.gnomAD.r2.1.GRCh38

**Comment by gevro** [comment]
I'm also getting these errors in the demo:
```
[Thu Dec 24 11:37:49 2020]
rule aberrantExpression_dependency:
    output: /gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-expression-pipeline_dep.svg
    jobid: 9

WARNING: Less than 30 IDs in DROP_GROUP outrider
WARNING: Less than 30 IDs in DROP_GROUP import_exp
WARNING: Less than 30 IDs in DROP_GROUP fraser
check for missing R packages
Error: <stdin>: syntax error in line 1 near 'install'
Warning: syntax ambiguity - badly delimited number '.1.' in line 1 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '1.30.' in line 2 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '4.0.' in line 2 of <stdin> splits into two tokens
Warning: syntax ambiguity - badly delimited number '.1.' in line 3 of <stdin> splits into two tokens
```

**Comment by gevro** [comment]
And this error:
```
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
[Thu Dec 24 11:38:57 2020]
Error in rule aberrantExpression_dependency:
    jobid: 9
    output: /gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-expression-pipeline_dep.svg
    shell:
        snakemake --nolock --rulegraph /gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-expression-pipeline_index.html | dot -Tsvg -Grankdir=TB > /gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-expression-pipeline_dep.svg
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job aberrantExpression_dependency since they might be corrupted:
/gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-expression-pipeline_dep.svg
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /gpfs/scratch/evrong01/drop_demo/.snakemake/log/2020-12-24T113627.367518.snakemake.log
```
UPDATE: 'snakemake --unlock --cores 1' fixed this.

**Comment by gevro** [comment]
I think it would help to have a clean system, and trying to install it and running the demo. Since these are errors from the demo, it is not likely to be an issue with my system.

**Comment by gevro** [comment]
Demo finished successfully. I will now try on our own samples.

**Comment by vyepez88** [comment]
Thanks for all the updates. I created a new session for today's fix to be sure that the BSgenome38 installation worked. 
I will update the documentation to reflect the --update option.
I'm not sure why the automatic `mafDb` installation didn't work through BiocInstall, on my system installing `devtools` wasn't working, but the rest of packages were. Manual installation usually overcomes this.
We have indeed some problems with the rule to create the rule graph, but for me it ran though in the demo without having to unlock it. I'll investigate why or maybe remove that rule. In any case, creating the rule graph doesn't affect the rest of the pipeline, so running it with the `-k` option will run the whole pipeline except for that step.
Hope it works with your samples now.

**Comment by gevro** [comment]
Thanks. I think the issue with MAF might be it is a large package, 5-6 Gb. It might be triggering some kind of timeout.

**Comment by gevro** [comment]
I'm getting this error even though I did snakemake --unlock --cores 1

```
rule aberrantSplicing_dependency:
    output: /gpfs/scratch/evrong01/drop_demo/Output/html/aberrant-splicing-pipeline_dep.svg
    jobid: 13

WARNING: Less than 30 IDs in DROP_GROUP outrider
WARNING: Less than 30 IDs in DROP_GROUP import_exp
WARNING: Less than 30 IDs in DROP_GROUP fraser
check for missing R packages
Structuring dependencies...
Dependencies file generated at: /tmp/tmpc22afkq1

Building DAG of jobs...
Error: Directory cannot be locked. This usually means that another Snakemake instance is running on this directory. Another possibility is that a previous run exited unexpectedly.
```

**Comment by gevro** [comment]
I am also getting this error in the demo with hg38:
```
Thu Dec 24 13:04:42 2020: Count split reads for sample: HG00176.4.M_120208_2_trunc
Warning message:
In countSplitReads(sampleID = sample_id, fds = fds, NcpuPerSample = snakemake@threads,  :
  Not counting chromosome(s) chr21 in sample HG00176.4.M_120208_2_trunc as it has a different length in the bamFile of this sample than in the provided genome.
```

UPDATE: This is probably due to the demo not being aligned to hg38.

**Comment by gevro** [comment]
Looks like it is working now on my samples! I will update if any other issues.
When will the Bsgenome branch merge with the main version?

**Comment by vyepez88** [comment]
great! 
Indeed the warning is due to the demo being aligned to hg19.

**Comment by gevro** [comment]
Thanks. I will let you know if we find any new splicing mutations with DROP.
