### ISSUE TITLE
Error in rule mae_QC_reChrVCF

### ISSUE THREAD

**Issue by csaygi** [gagneurlab/drop#182]
Hello everyone,

I am getting "Error in rule mae_QC_reChrVCF" while running the mae pipeline. I hope we can find a way to make it work.

I thought the error could be due to the GATK4 ASEReadCounter part and ran it independent from the pipeline. Indeed, read groups were missing in the bam files and there were two variants in some positions of the vcf files. I fixed all of them by using picard AddOrReplaceReadGroups and GATK4 SelectVariants. ASEReadCounter ran without any problem and output the allelic counts for all samples now.

However, when I ran DROP with these fixed bam and vcf files, drop produced the same error again. It displayed the error, continued working for around two hours, calculated allelic counts for only 4 vcf-bam pairs and then quited (there are 13 vcf-bam pairs in total). Even though processed results folder is empty, these files are at the processed data folder.

the details of the error:
Error in rule mae_QC_reChrVCF:
    jobid: 50
    output: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
    shell:
        
        echo 'converting from UCSC to NCBI format'
        bcftools annotate --rename-chrs Scripts/MonoallelicExpression/pipeline/resource/chr_NCBI_UCSC.txt /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/qc_vcf_1000G_GRCh38.vcf.gz             | bgzip > /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
        bcftools index -t /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job mae_QC_reChrVCF since they might be corrupted:
/home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz

config.yaml:
projectTitle: "DROP: Detection of RNA Outliers Pipeline"
root:             /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/
htmlOutputPath:   /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/
indexWithFolderName: true # whether the root base name should be part of the index name

hpoFile: null  # if null, downloads it from webserver 
sampleAnnotation: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/sample_annotation.tsv

geneAnnotation:
    # multiple annotations with custom names are possible
    # <annotation_name> : <path to gencode v29 annotation>
    v29:  /mnt/ref/Homo_sapiens/Ensembl/Homo_sapiens.GRCh38.103.gtf

genomeAssembly: GRCh38  # either hg19/hs37d5 or hg38/GRCh38
exportCounts:
    # specify which gene annotations to include and which 
    # groups to exclude when exporting counts
    geneAnnotations:
      - v29

mae:
    groups:
        - mae
    genome: /mnt/ref/Homo_sapiens/Ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa      # path to genome sequence in fasta format
    gatkIgnoreHeaderCheck: true
    padjCutoff: .05
    allelicRatioCutoff: 0.8
    addAF: false
    maxAF: .001
    maxVarFreqCohort: .05
    # VCF-BAM matching
    qcVcf: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/qc_vcf_1000G_GRCh38.vcf.gz       # path to common variant file e.g. qc_vcf_1000G.vcf.gz
    qcGroups: mae

tools:
    gatkCmd: gatk
    bcftoolsCmd: bcftools
    samtoolsCmd: samtools

**Comment by nickhsmith** [comment]
We are in the (internal) process of updating drop to fix these errors. We hope to have it reviewed and made available soon, if you feel comfortable you can install/use the  `QOL_changes_real` branch which may provide the fix you need.

**Comment by nickhsmith** [comment]
We have just pushed changes to the `dev` branch. If you were to pull those changes and run `drop update` in your working directory it should update the code such that your problems are fixed. If not please let us know and we will try our best to help you get everything working.

A note about the new changes, we've implemented some changes to the structure/organization. because of this, you may see some additional warnings, but otherwise no changes are necessary from your end.

**Comment by csaygi** [comment]
Thank you for the update! unfortunately, the error I posted still persists.

**Comment by nickhsmith** [comment]
I'm sorry to hear that. In the `dev` branch we are using a different rule/method to match the bam and vcf stylings. Could you please send us the new error report?

Please also make sure that the dev branch is properly installed. You can do by following the [documentation here](https://gagneurlab-drop.readthedocs.io/en/latest/installation.html#other-drop-versions)

**Comment by csaygi** [comment]
Thank you for your reply! I installed DROP via pip install git + https: //github.com/gagneurlab/drop.git@dev and in a conda environment. Here is the log file starting from the error:

[Wed May 5 15:54:05 2021]
Error in rule mae_QC_reChrVCF:
    jobid: 50
    output: /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
    shell:
        
        echo 'converting from UCSC to NCBI format'
        bcftools annotate --rename-chrs Scripts / MonoallelicExpression / pipeline / resource / chr_NCBI_UCSC.txt /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/qc_vcf_1000G_GRCh38.vcf.gz | bgzip> /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
        bcftools index -t /home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job mae_QC_reChrVCF since they might be corrupted:
/home/csaygi/csaygi/rnaseq/MAE/drop_run_trial/processed_data/mae/qc_vcf_ncbi.vcf.gz
[Wed May 5 15:54:08 2021]
Finished job 75.
1 of 64 steps (2%) done
[Wed May 5 15:54:23 2021]
Finished job 18.
2 of 64 steps (3%) done
[Wed May 5 15:54:30 2021]
Finished job 39.
3 of 64 steps (5%) done
[Wed May 5 15:54:33 2021]
Finished job 24.
4 of 64 steps (6%) done
[Wed May 5 15:54:34 2021]
Finished job 3.
5 of 64 steps (8%) done
[Wed May 5 15:54:35 2021]
Finished job 7.
6 of 64 steps (9%) done
[Wed May 5 18:07:39 2021]
Finished job 26.
7 of 64 steps (11%) done
[Wed May 5 18:24:11 2021]
Finished job 29.
8 of 64 steps (12%) done
[Wed May 5 19:02:21 2021]
Finished job 11.
9 of 64 steps (14%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message.

**Comment by nickhsmith** [comment]
I think that because we don't bump the version in the dev branch the new dev installation isn't being recognized. Could you please run the following to force the new installation:
 ```
pip install --force-reinstall --no-deps git+https://github.com/gagneurlab/drop.git@dev
drop update
 ```
 
 If all things go well you should see a print out of all the files that are overwritten to the current dev version, ending with 
 
```
updating local Scripts if necessary
update...done
```

And then hopefully the issue will be fixed, or at least a new problem comes up that we can try to solve. Thank you for your patience!

**Comment by csaygi** [comment]
I forced the new installation and it worked, thank you one more time!

**Comment by vyepez88** [comment]
great news! thanks for letting us know.
