### ISSUE TITLE
AberrantExpression - MissingInputException: Missing input files for rule markdown

### ISSUE THREAD

**Issue by Kriquin-UN** [gagneurlab/drop#310]
Hi,

I raise an error while running snakemake aberrantExpression : 

```
WorkflowError:
WorkflowError:
    WorkflowError (rule AberrantExpression_pipeline_Counting_mergeCounts_R, line 135, /tmp/tmp6938r_2i):
        Function did not return str or list of str.
    MissingInputException: Missing input files for rule markdown:
        output: /shared/projects/neurodev_rnaseq/drop_pipeline/reports/AberrantExpression/Counting/v34/Summary_run.html
        wildcards: file=AberrantExpression/Counting/v34/Summary_run
        affected files:
            AberrantExpression/Counting/v34/Summary_run.md
MissingInputException: Missing input files for rule markdown:
    output: /shared/projects/neurodev_rnaseq/drop_pipeline/reports/Scripts_AberrantExpression_pipeline_Counting_Datasets.html
    wildcards: file=Scripts_AberrantExpression_pipeline_Counting_Datasets
    affected files:
        Scripts_AberrantExpression_pipeline_Counting_Datasets.md
```
Here attached sample annotation and config files. 

Do you have a solution to this problem ? 

Thanks in advance, 

Kevin

[sample_anno.txt](https://github.com/gagneurlab/drop/files/8254997/sample_anno.txt)

[config.txt](https://github.com/gagneurlab/drop/files/8254996/config.txt)

**Comment by nickhsmith** [comment]
Hi, sorry you are having errors. Did the pipeline run at all or how did you run the pipeline? Do you have a full log file that you can share?

Are you using DROP version 1.1.3? (`drop --version`).

It's hard to diagnose the problem unfortunately without more information.

1. Could you please confirm that you are using DROP 1.1.3 (and have run `drop update` to make sure your local directory is also up to date)
2. Could you please check if `snakemake aberrantExpression -n` runs without errors?

Thank you.

**Comment by Kriquin-UN** [comment]
Thanks a lot for your reply. 

I use version 1.1.3 and local directory is updated. No log file was generated. 
I also have this error message with the dry run. 
But I can run the demo dataset without any problem. 

Let me know if you need more details.

**Comment by nickhsmith** [comment]
Could you please delete the values in the `GENE_ANNOTATION` column in the `sample_anno.tsv` file Those should only be populated in the case of external counts. I believe that should fix it.

**Comment by Kriquin-UN** [comment]
You are right.  It works now. 
Thank you very much for your quick answer.

**Comment by lbundalian** [comment]
Hi. I have an updated version of DROP but the problem still occurs. I dont have anything listed in the gene annotation column
