### ISSUE TITLE
Can't install v1.5.0

### ISSUE THREAD

**Issue by gevro** [gagneurlab/drop#647]
Trying to create a new conda environment for v1.5.0 per instructions, but it is installing v1.2.2:
drop               bioconda/noarch::drop-1.2.2-pyhdfd78af_0

Then I did pip uninstall drop

Then pip install git+https://github.com/gagneurlab/drop.git@1.5.0

That installed, but running drop gives this error:

$ drop -version
Traceback (most recent call last):
  File "/gpfs/home/bin/drop-conda/bin/drop", line 5, in <module>
    from drop.cli import main
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/gpfs/home/in/drop-conda/lib/python3.10/site-packages/drop/config/DropConfig.py", line 3, in <module>
    from .SampleParams import SampleParams
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/drop/config/SampleParams.py", line 9, in <module>
    pd.set_option("future.no_silent_downcasting", True)
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/pandas/_config/config.py", line 263, in __call__
    return self.__func__(*args, **kwds)
  File "/gpfs/home/bin/drop-conda/lib/python3.10/site-packages/pandas/_config/config.py", line 156, in _set_option
    key = _get_single_key(k, silent)
  File "/gpfs/home/evrong01/bin/drop-conda/lib/python3.10/site-packages/pandas/_config/config.py", line 121, in _get_single_key
    raise OptionError(f"No such keys(s): {repr(pat)}")
pandas._config.config.OptionError: No such keys(s): 'future.no_silent_downcasting'

**Comment by AtaJadidAhari** [comment]
Hi @gevro, the new release is not yet on bioconda, that's why you couldn't install the latest version through conda. We have updated the recipes on bioconda and hopefully it will be available via conda soon.
In the meantime, I uploaded the DROP_1.5.0.yaml file to our [public service ](https://www.cmm.in.tum.de/public/paper/drop_analysis/). Can you try to install DROP_1.5.0 using that? You can do so by calling `mamba env create -f DROP_1.5.0.yaml`.

**Comment by c-mertes** [comment]
The PR bioconda/bioconda-recipes/pull/60218 just got merged. Can you try with a fresh conda environment and install drop from there? 

```
mamba create -n drop-1-5-0 "drop>=1.5.0"
```

**Comment by gevro** [comment]
Installed, but drop is not working:
```
drop --version                                                                                                                                      
(/gpfs/home/g01/lab/bin/drop-conda) [g01@cn-0045 drop]$ drop --version                                                              
Traceback (most recent call last):                                                                                                                  
  File "/gpfs/home/g01/lab/bin/drop-conda/bin/drop", line 6, in <module>                                                                 
    from drop.cli import main                                                                                                                       
  File "/gpfs/home/g01/lab/bin/drop-conda/lib/python3.9/site-packages/drop/__init__.py", line 1, in <module>                             
    from .setupDrop import *                                                                                                                        
  File "/gpfs/home/g01/lab/bin/drop-conda/lib/python3.9/site-packages/drop/setupDrop.py", line 2, in <module>                            
    from drop.config.DropConfig import DropConfig
  File "/gpfs/home/g01/lab/bin/drop-conda/lib/python3.9/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/gpfs/home/g01/lab/bin/drop-conda/lib/python3.9/site-packages/drop/config/DropConfig.py", line 3, in <module>
    from .SampleParams import SampleParams
  File "/gpfs/home/g01/lab/bin/drop-conda/lib/python3.9/site-packages/drop/config/SampleParams.py", line 9, in <module>
    pd.set_option("future.no_silent_downcasting", True)
  File "/gpfs/home/g01/.local/lib/python3.9/site-packages/pandas/_config/config.py", line 256, in __call__
    return self.__func__(*args, **kwds)
  File "/gpfs/home/g01/.local/lib/python3.9/site-packages/pandas/_config/config.py", line 149, in _set_option
    key = _get_single_key(k, silent)
  File "/gpfs/home/g01/.local/lib/python3.9/site-packages/pandas/_config/config.py", line 114, in _get_single_key
    raise OptionError(f"No such keys(s): {repr(pat)}")
pandas._config.config.OptionError: "No such keys(s): 'future.no_silent_downcasting'"
```

**Comment by c-mertes** [comment]
We did not set the requirement correctly, but we do require pandas 2.2 or higher. I think you somehow pull a older version from pandas into your environment and hence you get this error. 

If you update pandas to 2.2 all should be good. 

Can you verify it by running: 

```
conda update "pandas>=2.2"
drop --version
```

**Comment by gevro** [comment]
Now the basic conda installation is not working:

(by the way, have you all considered making a docker to resolve various dependency issues for installations? It would make things easier for users I think).

conda create -p ~/evronylab/bin/drop-conda -c conda-forge -c bioconda --override-channels "drop>=1.5.0"
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - drop[version='>=1.5.0']

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch

**Comment by c-mertes** [comment]
Hi @gevro,

based on your comment, do I assume correctly that you do not have a dedicated conda environment for drop? 

From experience, we do recommend to have for every workflow or tooling a separated dedicated conda environment to not run into incompatibility issues as you describe. 

Can you try again to create a new and fresh conda env and then in stall drop in it? 

```
conda create -n drop-new "drop>=1.5.0" 
conda activate drop-new
drop --version
```

If it still does not work can you paste the result of 

```
conda list
```

Regarding the DOCKER image, there is usually an autobuild docker image from bioconda through biocontainers https://biocontainers.pro/tools/drop

There are no plans right now, but there is also an issue for a docker image here https://github.com/gagneurlab/drop/pull/586

**Comment by gevro** [comment]
Sorry, I'm getting this error. There is some problem with drop 1.5.0 on conda.

Regarding the docker issue, I think moving the drop system entirely to docker and having that be the only distribution channel would be worthwhile. It would prevent installation/dependency issues that are common with conda environments, since conda is still quite dependent on the local computing system's configuration.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - drop[version='>=1.5.0']

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by gevro** [comment]
Hi, Just checking if any update. Thanks!

**Comment by AtaJadidAhari** [comment]
Hi @gevro, can you try installing through conda again? It should work now.

**Comment by gevro** [comment]
The package is still not available:
PackagesNotFoundError: The following packages are not available from current channels:

  - drop[version='>=1.5.0']

**Comment by AtaJadidAhari** [comment]
Weird, as it is already listed [here](https://bioconda.github.io/recipes/drop/README.html) and I installed it on my side that is why I asked you to check again. Could be a conda cache issue (try `conda clean`) or maybe you forgot to add `-c bioconda`? 

<img width="614" height="548" alt="Image" src="https://github.com/user-attachments/assets/7a8a0973-5977-4923-b286-1ecb0ca2e72e" />

**Comment by gevro** [comment]
Thanks, clearing the cache worked!
